name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
      
jobs:
  AppImage:
    runs-on: ubuntu-latest
    steps:
    - name: Create AppImage
      run: |
           sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get -y install desktop-file-utils
           sudo apt-get update && sudo apt-get -y install xdg-desktop-portal xdg-desktop-portal-gnome
           wget "https://raw.githubusercontent.com/AppImage/pkg2appimage/master/pkg2appimage"
           bash -ex pkg2appimage Zoom
    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: AppImage
        automatic_release_tag: stable
        prerelease: false
        draft: false
        files: |
          out/*.AppImage*
        repo_token: ${{ secrets.GITHUB_TOKEN }}
