name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
      
jobs:
  AppImage:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - uses: AppImageCrafters/build-appimage@master
      with:
        recipe: "./zoom.yml"
    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: AppImage
        automatic_release_tag: stable
        prerelease: false
        draft: false
        files: |
          out/*.AppImage*
        repo_token: ${{ secrets.GITHUB_TOKEN }}
